### ISSUE TITLE
TODO: Exercise 5-7

### ISSUE THREAD

**Issue by jhelphenstine** [jhelphenstine/c-programming-language#14]
Rewrite `readlines` to store lines in an array supplied by `main`, rather than calling `alloc` to maintain storage.

- [x] Transcribe the supporting source files, including alloc
- [x] Modify the provided `readlines` to use an array supplied by `main`
- [x] Measure code execution time difference between these implementations
- [x] Test & verify results
